version: 2
updates:
  - package-ecosystem: "github-actions"  # For GitHub Actions workflows
    directory: "/"
    schedule:
      interval: "weekly"

  - package-ecosystem: "npm"  # For Node.js/npm projects
    directory: "/"
    schedule:
      interval: "weekly"
