name: Continuous Integration

# 🔹 Trigger workflow on every push or pull request to main
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  ci:
    name: Run Linting, Tests, and Build Checks
    runs-on: ubuntu-latest

    # Use stable Node.js versions compatible with modern ESLint
    strategy:
      matrix:
        node-version: [18.18.x, 20.x]

    steps:
    # Step 1: Checkout repository code
    - name: Checkout code
      uses: actions/checkout@v4

    # Step 2: Setup Node.js
    - name: Setup Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'

    # Step 3: Install dependencies
    - name: Install dependencies
      run: npm ci || npm install

    # Step 4: Run ESLint for linting errors and warnings
    - name: Run ESLint
      run: |
        if [ -d "src" ]; then
          npx eslint src/**/*.js
        else
          echo "No src directory found, skipping linting..."
        fi

    # Step 5: Check code formatting using Prettier
    - name: Check code formatting
      run: |
        npx prettier --check "**/*.js" "**/*.html" "**/*.css"

    # Step 6: Run project tests (if defined)
    - name: Run tests
      run: |
        if grep -q '"test"' package.json; then
          npm test
        else
          echo "No tests defined, skipping..."
        fi

    # Step 7: Optional build step (for Node or React projects)
    - name: Build project
      run: |
        if grep -q '"build"' package.json; then
          npm run build
        else
          echo "No build script found, skipping..."
        fi

    # Step 8: Upload results (for visibility)
    - name: Upload test and lint results
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: ci-results-${{ matrix.node-version }}
        path: |
          coverage/
          test-results/
        retention-days: 7

    # Step 9: Final feedback in logs
    - name: Summary
      if: always()
      run: |
        echo "Continuous Integration complete."
        echo "Node version: ${{ matrix.node-version }}"
        echo "Check ESLint, Prettier, and Test results above."

