name: Continuous Integration

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  ci:
    name: Run Linting, Tests, and Build Checks
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x]

    steps:
      # Step 1: Checkout repository code
      - name: Checkout code
        uses: actions/checkout@v4

      # Step 2: Set up Node.js environment
      - name: Setup Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v6
        with:
          node-version: ${{ matrix.node-version }}
          cache: npm

      # Step 3: Install dependencies
      - name: Install dependencies
        run: npm install

      # Step 4: Run ESLint
      - name: Run ESLint
        run: |
          npm install eslint --save-dev
          npx eslint . || echo "Linting completed with warnings"

      # Step 5: Run tests (if available)
      - name: Run Tests
        run: |
          if [ -f "package.json" ] && grep -q '"test"' package.json; then
            npm test || (echo "Tests failed" && exit 1)
          else
            echo "No test script found, skipping tests"
          fi

      # Step 6: Build project (if build script exists)
      - name: Run Build
        run: |
          if [ -f "package.json" ] && grep -q '"build"' package.json; then
            npm run build || (echo "Build failed" && exit 1)
          else
            echo "No build script found, skipping build"
          fi

      # Step 7: Report CI Status
      - name: Report Status
        run: |
          echo "CI completed successfully for Node.js version ${{ matrix.node-version }}"

