name: Code Review Workflow

on:
  pull_request:
    branches:
      - main
    types: [opened, synchronize, reopened]

jobs:
  review:
    name: Automated Code Review
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code from the PR
      - name: Checkout Code
        uses: actions/checkout@v4

      # Step 2: Setup Node.js (adjust version if needed)
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: npm

      # Step 3: Install dependencies
      - name: Install Dependencies
        run: npm install

      # Step 4: Run ESLint to check code standards
      - name: Run ESLint (Code Style Check)
        run: |
          npm install eslint --save-dev
          npx eslint . || echo "Lint warnings found"

      # Step 5: Run Code Quality Scan using SonarJS (lightweight)
      - name: Run Code Quality Check
        run: |
          npm install eslint-plugin-sonarjs --save-dev
          npx eslint . --plugin sonarjs || echo "Quality issues found"

      # Step 6: Basic Security Scan using npm audit
      - name: Security Vulnerability Scan
        run: |
          npm audit --audit-level=moderate || echo "Security issues found"

      # Step 7: Provide review summary feedback
      - name: Post Review Summary
        run: |
          echo "✅ Automated Code Review completed for PR #${{ github.event.pull_request.number }}"
          echo "Linting, quality, and security checks have been executed."

