name: Code Review Workflow

on:
  pull_request:
    branches:
      - main
    types: [opened, synchronize, reopened]

jobs:
  review:
    name: Automated Code Review
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code from the PR
      - name: Checkout Code
        uses: actions/checkout@v4

      # Step 2: Setup Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v6
        with:
          node-version: 18
          cache: npm

      # Step 3: Install dependencies
      - name: Install Dependencies
        run: npm install

      # Step 4: Run ESLint to check code standards
      - name: Run ESLint (Code Style Check)
        run: |
          npm install eslint --save-dev
          npx eslint . && echo "ESLINT_STATUS=pass" >> $GITHUB_ENV || echo "ESLINT_STATUS=warnings" >> $GITHUB_ENV

      # Step 5: Run Code Quality Scan using SonarJS
      - name: Run Code Quality Check
        run: |
          npm install eslint-plugin-sonarjs --save-dev
          npx eslint . --plugin sonarjs && echo "QUALITY_STATUS=pass" >> $GITHUB_ENV || echo "QUALITY_STATUS=issues" >> $GITHUB_ENV

      # Step 6: Basic Security Scan using npm audit
      - name: Security Vulnerability Scan
        run: |
          npm audit --audit-level=moderate && echo "SECURITY_STATUS=pass" >> $GITHUB_ENV || echo "SECURITY_STATUS=vulnerabilities" >> $GITHUB_ENV

      # Step 7: Provide detailed review summary feedback
      - name: Post Review Summary
        run: |
          echo "CODE REVIEW SUMMARY" >> $GITHUB_STEP_SUMMARY
          echo "===================" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "Pull Request: #${{ github.event.pull_request.number }}" >> $GITHUB_STEP_SUMMARY
          echo "Branch: ${{ github.head_ref }}" >> $GITHUB_STEP_SUMMARY
          echo "Review Date: $(date)" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "CHECK RESULTS:" >> $GITHUB_STEP_SUMMARY
          echo "-------------" >> $GITHUB_STEP_SUMMARY
          echo "- ESLint Code Style: ${{ env.ESLINT_STATUS == 'pass' && 'PASS - No linting issues found' || 'WARNINGS - Code style issues detected' }}" >> $GITHUB_STEP_SUMMARY
          echo "- Code Quality (SonarJS): ${{ env.QUALITY_STATUS == 'pass' && 'PASS - No quality issues found' || 'ISSUES - Code quality concerns identified' }}" >> $GITHUB_STEP_SUMMARY
          echo "- Security Audit: ${{ env.SECURITY_STATUS == 'pass' && 'PASS - No vulnerabilities found' || 'VULNERABILITIES - Security issues detected' }}" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "SUMMARY:" >> $GITHUB_STEP_SUMMARY
          echo "-------" >> $GITHUB_STEP_SUMMARY
          echo "Automated code review completed. Please review any warnings or issues identified above." >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "Note: This is an automated review. Manual code review is still recommended." >> $GITHUB_STEP_SUMMARY
