name: Documentation Deployment

on:
  push:
    branches: [main]
    paths:
      - "docs/**"
      - ".github/workflows/deploy-docs.yml"

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    permissions:
      contents: write    # ✅ Allows pushing to another branch (required for gh-pages)

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v6
        with:
          node-version: 18

      - name: Install documentation dependencies
        run: npm install -g docsify-cli

      - name: Build documentation
        run: docsify init ./docs || echo "Docs already initialized"

      - name: Deploy documentation to docs-pages branch
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs
          publish_branch: docs-pages

