name: Generate Release Notes

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  notes:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Create release notes
        uses: mikeal/release-notes-action@v2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
