name: Weekly Scraper Run

on:
  schedule:
    - cron: "0 2 * * 0"
  workflow_dispatch:

jobs:
  scrape:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 18.x
      - run: npm install
      - run: node run.js
      - name: Upload new data
        uses: actions/upload-artifact@v4
        with:
          name: weekly-scrape
          path: public/data
